name: 记录成长

project:
    version: fong
    homepage: https://fongyq.github.io/

license:
    software: MIT License
    software_url: http://opensource.org/licenses/MIT

links:
    header:
      - title: GitHub
        url: https://github.com/fongyk
    footer:
      - title: GitHub
        url: https://github.com/fongyk

ui:
    header:
        color1: "#080331"
        color2: "#673051"
        trianglify: true

social:
    github:
        enabled: false
        user: 
        repo: 
    twitter:
        enabled: false
        via:
        hash:
        account:
    facebook:
        enabled: false
        profileUrl:

analytics:
    google: UA-123456-1

# Build settings
markdown: kramdown
exclude:
    - Gemfile
    - Gemfile.lock
theme: jekyll-theme-cayman